### ISSUE TITLE
Newest 1.18 version: unable to open loot chests

### ISSUE THREAD

**Issue by awesomestpie** [Thelnfamous1/Dungeons-Gear#179] opened 2022-12-24 00:54 UTC
Hi! 
[latest.log](https://github.com/Thelnfamous1/Dungeons-Gear/files/10297783/latest.log)

**Comment by awesomestpie** [comment] 2022-12-24 08:20
Hope u will fix it soon!

**Comment by Patrigan** [comment] 2023-01-02 20:31
Duplicate of #175. Will be fixed once I port that fix to 1.18.2

**Closed as completed by Patrigan** 2023-01-02 20:31 UTC
