### ISSUE TITLE
1.16.4 Massive SP Lag When Mod is present

### ISSUE THREAD

**Issue by MokahTGS** [Thelnfamous1/Dungeons-Gear#23] opened 2020-12-19 18:13 UTC
I'm not sure what is going on but adding either Dungeon Mobs or Dungeon Gear is causing a massive lag spike every few seconds when I create a new world in SP.

Dungeon Mobs 1.16.4.1.0.2
Dungeon Gear 1.16.4.3.0.4

Removing the mods allows me to create a world and it performs as normal.

Our full mod list: https://pastebin.com/Uq4XeJ9a

Perhaps there is some sort of bad mod interaction or something is causing a freak out.

**Comment by Thelnfamous1** [comment] 2020-12-19 19:11
I need a latest.log to be able to help you at all.

**Comment by MokahTGS** [comment] 2020-12-19 22:05
Logs: https://www.dropbox.com/s/h4y5vr5970frht5/logs.7z?dl=0

**Comment by Thelnfamous1** [comment] 2020-12-19 22:37
Can't open it.

**Comment by MokahTGS** [comment] 2020-12-19 22:54
7z zip file

**Comment by MokahTGS** [comment] 2020-12-20 00:01
https://www.dropbox.com/s/gpvicaj3rc6axt4/logs.zip?dl=0

Try that.

**Comment by Thelnfamous1** [comment] 2020-12-20 00:29
Unfortunately, the logs tell me nothing specifically about my mods that indicate lag. In the debug log most of it shows that Enigmatic legacy is doing something with a lot of loot tables, but I don't even know if that is relevant.

**Comment by MokahTGS** [comment] 2020-12-20 00:30
Yeah, I don't know what it is but taking out the dungeon mods solves the problem.

:(

**Comment by Thelnfamous1** [comment] 2020-12-20 00:31
Have you tried removing only 1 of the dungeons mods at a time?

**Comment by MokahTGS** [comment] 2020-12-20 00:32
Yes, Leaving the gear mod in produces the issue.

**Comment by MokahTGS** [comment] 2020-12-20 00:33
You could also try to reproduce the issue.  I'm using a modified version of the TNP Limitless 3 Modack.

**Comment by Thelnfamous1** [comment] 2020-12-20 00:36
Ah okay. I imagine there's a lot of lag caused by loot injection somehow, that's the main thing that Dungeons Gear does that could conceivably cause lag spikes. Perhaps try removing other mods that affect loot generation (Enigmatic Legacy seemingly does something funky there) while leaving Dungeons Gear in and see what causes the problem.

My laptop unfortunately is too weak to handle that modpack's size so I cannot test it myself.

**Comment by Thelnfamous1** [comment] 2021-05-11 03:11
Fixed this bug in dev, will be fixed in next release

**Closed by Thelnfamous1** 2021-05-11 03:11 UTC
