### ISSUE TITLE
Items doing little to no damage

### ISSUE THREAD

**Issue by oaki555** [Thelnfamous1/Dungeons-Gear#160] opened 2022-07-13 19:29 UTC
My dungeons gear items are doing pretty much no damage and the attack speed is super quick no matter what, I can hit crits over and over. I checked config files but couldnt find anything.

**Comment by Patrigan** [comment] 2022-07-14 02:39
this sounds like an issue with the datapack. Are you playing locally or on a server?
Which items?

**Comment by SanderBoelaars** [comment] 2022-07-14 18:14
Hello, I noticed this issue too. I tested a bunch of melee weapons and they all do very little damage. I also noticed some of the enchantments do not show up correctly, and instead of a normal name like Gravity Shot I it says: enchantment.dungeons_gear.gravity_shot I

I noticed this with the following enchantments:
enchantment.dungeons_gear.dodge I
enchantment.dungeons_gear.dodge II
enchantment.dungeons_gear.dodge III
enchantment.dungeons_gear.exploding_shot I
enchantment.dungeons_gear.exploding_shot II
enchantment.dungeons_gear.exploding_shot III
enchantment.dungeons_gear.gravity_shot I
enchantment.dungeons_gear.gravity_shot II
enchantment.dungeons_gear.gravity_shot III
enchantment.dungeons_gear.harpoon_shot
enchantment.dungeons_gear.velocity I
enchantment.dungeons_gear.velocity II
enchantment.dungeons_gear.velocity III
enchantment.dungeons_gear.void_dodge I
enchantment.dungeons_gear.void_dodge II
enchantment.dungeons_gear.void_dodge III

I run the mod on a server.

**Comment by Patrigan** [comment] 2022-07-15 04:11
Same question, single player or on a server?

The translations are known and will be fixed soon.

**Comment by SanderBoelaars** [comment] 2022-07-15 14:03
I run the mod on a sever.

**Comment by bituron680** [comment] 2022-07-17 14:23
the bug most exactly is the weapons has the damage and the coldown of the fist and the shields dont protect from proyectiles, Me and some friends test in a server and individualy.

**Comment by Patrigan** [comment] 2022-07-17 17:33
which version, latest beta?

**Comment by bituron680** [comment] 2022-07-17 18:34
yes the version 
dungeons_gear-1.16.5-3.1.14-beta

**Comment by Patrigan** [comment] 2022-07-19 16:45
Confirmed the bug. Will be fixed in next beta asap.

**Comment by Patrigan** [comment] 2022-07-21 14:02
I think, but due to a semi random nature of it, I can't be sure, that this is fixed in Dungeons Beta 3.1.15. Please confirm after release.

**Comment by Patrigan** [comment] 2022-07-21 14:02
Best that you do a /reload on the server

**Comment by Patrigan** [comment] 2022-07-25 07:19
Has anyone been able to confirm if this is fixed?

**Comment by Patrigan** [comment] 2022-08-13 22:05
I will assume it is fixed now! Make a new ticket if it isn't (after doing the above suggested /reload)

**Closed as completed by Patrigan** 2022-08-13 22:05 UTC
Labels: bug
