### ISSUE TITLE
[1.16.5] Incompatibility with Aquaculture 2 leeches

### ISSUE THREAD

**Issue by MarioSMB** [Thelnfamous1/Dungeons-Gear#44] opened 2021-02-10 15:30 UTC
For some reason, the leeches from Aquaculture 2 are unable to be used in alchemy, the cause was tracked down to this mod: https://github.com/TeamMetallurgy/Aquaculture/issues/207

**Comment by sscards55** [comment] 2021-02-10 22:13
There is a small chance it might have to do with capability implementations.

**Comment by Thelnfamous1** [comment] 2021-05-20 15:50
Is aquaculture expecting itemstacks without capabilities attached to them?

**Comment by sscards55** [comment] 2021-05-20 22:29
The issue is that the leeches from AQ are not able to be used a potion ingredients in the brewing stand. I have seen a similar issue before with Tinkers' Construct, where a stencil could not be used, and the cause was a mod attaching capabilities to every item in the game. I don't know if that's the case here, but I thought I would mentions it because it's a similar issue.

**Comment by Thelnfamous1** [comment] 2021-05-21 01:06
I do attach a capability to every ItemStack in the game, but to my knowledge it's necessary for the Fuse Shot and Accelerate enchantments to function, as they require reading stored data on an ItemStack to work

**Comment by Jackiecrazy** [comment] 2021-05-21 02:15
it should be sufficient to cover everything that has IShootable, no? It's only used for those items anyway, and those usually have complex enough architecture that other mods silently ignore most tags on them.

**Comment by Jackiecrazy** [comment] 2021-05-21 12:40
This should be fixed by 0b3f1ad.

**Closed** 2021-06-04 17:45 UTC
