### ISSUE TITLE
Moon dagger doesn't work

### ISSUE THREAD

**Issue by AceKrieger** [Thelnfamous1/Dungeons-Gear#209] opened 2023-01-25 01:41 UTC
I try to attack with the moon dagger, and it automatically switches it to my off hand, where I can't attack with it. I'm using the mod as part of the Roguelike Adventures & Dungeons 2. May also occur with other daggers, haven't tested it.

**Comment by Thelnfamous1** [comment] 2023-01-25 03:24
This is a feature for Daggers, once you land an attack it immediately switches places with your offhand weapon. I believe the intention is for Daggers to facilitate rapid weapon-swapping like you would see in PvP fights.

**Comment by Thelnfamous1** [comment] 2023-02-02 22:33
Closing as I personally verified that the moon dagger, as well as other dual wieldable weapons, are working as intended.

**Closed as completed by Thelnfamous1** 2023-02-02 22:33 UTC
