### ISSUE TITLE
Armor textures

### ISSUE THREAD

**Issue by Cybernin15** [Thelnfamous1/Dungeons-Gear#65] opened 2021-05-10 01:37 UTC
Armor textures are broken idk why no one is talking about it
![TEXURES](https://user-images.githubusercontent.com/83931908/117595366-af830a00-b151-11eb-980e-def4384f1b8e.png)
This should be a wither helmet

**Comment by Jackiecrazy** [comment] 2021-05-10 02:31
And the player shouldn't have that many curves. Is this epic fight?

**Comment by Cybernin15** [comment] 2021-05-10 02:33
> And the player shouldn't have that many curves. Is this epic fight?

ye

**Comment by Jackiecrazy** [comment] 2021-05-10 02:46
Duplicate of #57.

**Comment by Thelnfamous1** [comment] 2021-05-10 04:43
If the solution for this is to literally redo the code for every armor, I'm just going to say EFM is functionally incompatible with this mod.

**Comment by Quizer9O8** [comment] 2021-05-14 17:53
I really hope anyone of you can find another solution to make both parties happy as both mods bring realism and RPG together. It would be such a pitty if left unsolved.

**Comment by Jackiecrazy** [comment] 2021-05-15 02:47
Rea....lism?
Anyway, I'm useless with rendering, so if infamous doesn't want to do it, it's gotta be Patrigan or mgaray.

**Closed** 2021-05-18 19:08 UTC
Labels: duplicate

**Comment by Patrigan** [comment] 2021-10-10 09:16
You are surely welcome to make said pack and share it with us. As a team, we have collectively decided that Epic Fight Mod is too fiddly for us to spend time on right now.

If you know of any armor mod that adds armor on the level of Dungeons Gear that does work with Epic Fight Mod, feelf ree to share that as well.
