### ISSUE TITLE
[1.19.2] Crash while running Minecraft using Optifine

### ISSUE THREAD

**Issue by FirdausCraft10** [Thelnfamous1/Dungeons-Gear#227] opened 2023-02-26 02:01 UTC
This mod is one of my favorite mod, but please fix this unexpected crash

**Comment by Patrigan** [comment] 2023-04-03 18:37
Duplicate of #220

**Comment by Patrigan** [comment] 2023-04-03 18:37
Also, stop using Optifine. Use a combination of Rubidium, Occulus and CTM to get pretty much the same result, but just better , cleanerand more mod friendly.

**Closed as completed by Patrigan** 2023-04-03 18:37 UTC
