### ISSUE TITLE
SuperCharge enchant 0 damage level 4+

### ISSUE THREAD

**Issue by xThaySan** [Thelnfamous1/Dungeons-Gear#269] opened 2023-12-09 10:38 UTC
```
src/main/java/com/infamous/dungeons_gear/enchantments/ranged/SuperchargeEnchantment.java
```

This part of the code makes the damage zero when the enchantment is level 4 or higher :
```java
double damageModifier = 0;
if (superchargeLevel == 1) damageModifier = 1.2D;
if (superchargeLevel == 2) damageModifier = 1.4D;
if (superchargeLevel == 3) damageModifier = 1.6D;
arrow.setBaseDamage(originalDamage * damageModifier);
```

It may need to be modified to something like this:
```java
double damageModifier = 1.0D + 0.2D * superchargeLevel;
arrow.setBaseDamage(originalDamage * damageModifier);
```

**Comment by Thelnfamous1** [comment] 2024-02-10 03:20
Duplicate of #264. Slated to be fixed for 1.19.2 only.

**Closed as completed** 2024-02-14 01:52 UTC
